## WiSHFUL Agent config file

agent_info:
  name: 'unit_test'
  info: 'testing modules using local controller'
  iface: 'lo'

modules:
  simple:
      module : wishful_module_wifi
      class_name : WifiModule
      interfaces : ['lo', 'eno16777736']

  network:
      module : wishful_module_wifi
      class_name : NetworkModule

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule